config/routes.rb
Mau::Application.routes.draw do
  
  root :to => 'articles#index'
  resources :articles
  resources :dashboard
  resources :tags
  resources :comments
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  resources :articles do
    resources :comments
  end
end 












app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :article_id, :content, :user_id
  belongs_to :user
  belongs_to :article
  validates :content, :presence => true
   
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	def new
	  @comment = Comment.new
	end
  
	def create
	  @article = Article.find(params[:article_id])
	  @comment = @article.comments.build(params[:comment])
	  @comment.user_id = current_user.id
	  @comment.save
	    flash[:success] = "Comment created!"
	    redirect_to article_path(@comment.article)
	end

    def edit
     @comment =  Comment.find(params[:id])
     @article = @comment.article
     # @article = Article.find(params[:article_id])
     #@comment = @article.comments
    end   

    def update
     @comment = Comment.find(params[:id])
     @article = @comment.article
      if @comment.update_attributes(params[:comment])
        flash[:success] = "Comment updated!"
        redirect_to article_path(@article)
      else
       render :action => "edit" 
      end
    end

	def destroy

      @article = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
      @comment.destroy
      redirect_to article_path(@article) 
	end

end

app/views/comments/_comment.html.erb
<% if @article.comments.count  >= 1 %>
 <div id="comment-body">
  <div id="comment-inner-body"> 
    <div id="tabula"> 
      <ul id="tabula">
       <li> <div style="color: #0077CC;margin-right:10px; font-size: 1.0em;margin-top:8px;background-color:#;"> <strong> <%= comment.user.username if comment.user %></strong></div></li> 
       <li> <div style="color:;margin-right:0px; font-size: 1.0em;margin-top:8px;background-color:#;"> added a comment </div></li>
       <li> <div style="color: #0077CC; background-color:; margin-top:8px; margin-left:10px;"> <p> <%= time_ago_in_words(comment.created_at.in_time_zone("Asia/Calcutta"))  unless comment.created_at.nil? %> ago  </p></div></li>
      </ul>
     </div>  
    </div>
  <div id="comment-content"> 
    <%= comment.content %>
    </div>
      <div id="tabula"> 
       <ul id="tabula">
        <li> <div style="color: #0077CC; background-color:; margin-top:-8px; margin-left:0px;"> <%= link_to "edit", edit_article_comment_path(@article ,comment) %> </div></li>
         <li> <div style="color: #0077CC; background-color:; margin-top:-8px; margin-left:15px;"> <%= link_to 'Delete', article_comment_path(@article,comment), :confirm => 'Are you sure?', :method => :delete %> </div></li>
         <li> <div style="color: #0077CC; background-color:; margin-top:-8px; margin-left:15px;"> <%= link_to 'Reply' %> </div></li>
        </ul>
        </div>
        </div>
      <% else %>
     <div style="color:#0077CC;margin-left:25px;font-size:1.4em;"> be first to comment</div>
    <% end %>

  
 





app/views/comments/_comment_form.html.erb
<%= form_for ([@article, Comment.new]) do |f| %>
<div style="margin-top:10px;color:#1fb2e8;;margin-left:-33px; font-size:1.6em"><strong> Post your comments </strong> </div>
 <%= f.text_area :content, :style => "width:727px; height:100px; border: 1px solid #999999;margin-top:25px; background-color:#FFFFFF;margin-left:-33px" %>
     <div class="actions">
     <%= f.submit "add comment", :style => "margin-right:20px;width:25%; margin-left:560px; background-color:#66C9Ef; color:#FFFFFF; border: 0px solid #82b548; border-radius: 3px 3px 3px 3px; font-size: 1.3rem;" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
  <div style="border: 0px solid #1763A4;border-radius: 4px 4px 4px 4px;margin: 0 0 50px; padding: 20px 20px 10px; background: none repeat scroll 0 0 #ffffff; width: 100%; margin-left:110px">
   <div style="color:#0077CC;font-size: 2.0em;margin-left:-33px"> edit comment </div>
    <%= form_for ([@article, @comment]) do |f| %>
      <%= f.text_area :content, :style => "width:727px; height:150px; border: 1px solid #999999;margin-top:25px; background-color:#FFFFFF;margin-left:-33px" %>
   
      	<div style ="margin-top:20px; margin-left:430px;font-size:1.4em">  <%= link_to "cancel", article_path(@article) %> </div>
          <div> <%= f.submit "update comment",:style => "margin-top:-40px; margin-left:535px; background-color:#66C9Ef; color:#FFFFFF; font-size: 1.3rem; border: 0px solid #82b548; border-radius: 3px 3px 3px 3px;" %></div>
    <% end %>
 </div>

