config/routes.rb
Mau::Application.routes.draw do
  
  root :to => 'articles#index'
  resources :articles
  resources :dashboard
  resources :tags
  resources :comments
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  resources :articles do
    resources :comments
  end
end 












app/models/article.rb
class Article < ActiveRecord::Base
   attr_accessible :title, :body
   attr_accessible :tag_list
   has_many :comments, :dependent => :destroy
   belongs_to :user
   has_many :impressions, as: :impressionable
   has_many :taggings, :dependent => :destroy
   has_many :tags, through: :taggings 
   validates :title, :body, :tag_list,  :presence => true


   def tag_list
     self.tags.collect do |tag|
      tag.name
     end.join(", ")
   end

   def tag_list=(tags_string)
     tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
     new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by_name(name) }
     self.tags = new_or_found_tags
   end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_filter :is_user_admin, only: [:new, :create, :edit, :destroy]

    def is_user_admin
      redirect_to(action: :index) unless current_user.try(:is_admin?)
      return false
    end

   def log_impression
     @article = Article.find(params[:id])
     # this assumes you have a current_user method in your authentication system
      @article.impressions.create(ip_address: request.remote_ip,user_id:current_user.id)
   end

	  def index
		  #@articles = Article.where(is_draft:  false)
     # @articles = Article.all
      @article_titles = Article.first(10)
      @tags = Tag.all
      @articles = Article.paginate(:page => params[:page], :per_page => 5)
	  end

    def show
      @article = Article.find(params[:id])
      @related_articles = Article.joins(:taggings).where('articles.id != ?', @article.id).where(taggings: { tag_id: @article.tag_ids })
      @most_viewed_articles = Article.order('articles.impressions_count DESC').limit(5)

    end

	  def new
      @article = Article.new
	  end

    def create
      @article = Article.new(params[:article])
      @article.user_id = current_user.id
      if @article.save
        flash[:success] = "article created!"
        redirect_to article_path(@article)
      else
        render 'new'
      end
    end

    def edit
      @article = Article.find(params[:id])
    end

    def update
      @article = Article.find(params[:id])
      if @article.update_attributes(params[:article])
        flash.notice = "Article '#{@article.title}' Updated!"
        redirect_to article_path(@article)
        @article_update_user = current_user.id
      else
        render 'edit'
      end
    end

    def destroy
      @article = Article.find(params[:id])
      @article.destroy
      redirect_to action:  'index'
     end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_comment.html.erb
<% if @article.comments.count  >= 1 %>
  <div style="border: px solid #66c9ee;border-radius: 0px 0px 0px 0px;margin: 10px -30px 15px; padding: 	10px 15px 25px; background: none repeat scroll 0 0 #F2F2F2; width:700px; font-size: 1.2em;border-bottom: 0px solid #DDDDDD;">
      <%= comment.content %>
         <div id="tabula"> 
            <ul id="tabula">
             <li> <div style="color: #0077CC;margin-rigth:200px; font-size: 1.0em;margin-top:4px;background-color:#;"> <%= comment.user.username if comment.user %></div></li>
             <li> <div style="color: #0077CC; background-color:; margin-top:4px; margin-left:25px;"> <p> <%= time_ago_in_words(comment.created_at.in_time_zone("Asia/Calcutta"))  unless comment.created_at.nil? %>  </p></div></li>
            </ul>
           </div>
          </div>
    <% else %>
        <div style="color:#0077CC;margin-left:25px;font-size:1.4em;"> be first to comment</div>
  <% end %>
 






app/views/articles/_comment_form.html.erb

<%= form_for ([@article, @article.comments.build]), :required => true do |f| %>
 <%= f.hidden_field :article_id %> 
 <%= f.text_area :content, :style => "width:727px; height:100px; border: 1px solid #999999;margin-top:80px; background-color:#FFFFFF;margin-left:-33px" %>
    <div class="actions">
    <%= f.submit "Add Comment", :style => "margin-right:20px; margin-left:560px; background-color:#66C9Ef; color:#FFFFFF; border: 0px solid #82b548; border-radius: 3px 3px 3px 3px; font-size: 1.3rem;" %>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :class => '' } do |f| %>
<%= f.error_messages :header_message => "oops! you missed something",
  :message => "",
  :header_tag => :h3, :class => "background-color:#d24d33; color:#ffffff" %>
  <div>
    <%= f.label :title, :style => "margin-top:10px;" %>
    <div>
      <%= f.text_field :title, :style => "width:730px; height:30px; border: 1px solid #66c9ee;margin-top:10px; background-color:#FFFFFF;" %>
    </div>
  </div>
  <div>
    <%= f.label :body, :class => 'control-label' %>
   <%= f.text_area :body, :class => 'ckeditor' %>
  <%= f.label :tag_list, :style => "margin-top:10px" %><br />
  <%= f.text_field :tag_list, :style => "width:730px; height:30px; border: 1px solid #66c9ee;margin-top:0px; background-color:#FFFFFF;" %>
  <div style="margin-top: 20px">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                articles_path, :class => 'btn' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
  <div style="border: 0px solid #1763A4;border-radius: 4px 4px 4px 4px;margin: 0 0 50px; padding: 20px 20px 10px; background: none repeat scroll 0 0 #ffffff; width: 100%; margin-left:110px">
	 <div style="color:#0077CC;font-size: 2.0em"> edit article </div>
     <%= render :partial => 'form' %>
  </div>

app/views/articles/edit_comment.html.erb
<%= form_for ([@article, @article.comments.build]), :required => true do |f| %>
 <%= f.hidden_field :article_id %> 
 <%= f.text_area :content, :style => "width:727px; height:100px; border: 1px solid #999999;margin-top:80px; background-color:#FFFFFF;margin-left:-33px" %>
    <div class="actions">
    <%= f.submit "Add Comment", :style => "margin-right:20px; margin-left:560px; background-color:#66C9Ef; color:#FFFFFF; border: 0px solid #82b548; border-radius: 3px 3px 3px 3px; font-size: 1.3rem;" %>
  </div>
<% end %>

app/views/articles/index.html.erb
<%= will_paginate @articles %>
<table style="width="100%">
<tr>
<td style="width="400%">
<div style="border: 1px solid #B5B5B5;border-radius: 0px 0px 0px 0px; padding: px 2px 2px; background: none repeat scroll  0 0 #1fb2e8; ; width: 180%; margin-left:60px;margin-top:55px;" >

 <% @articles.each do |article| %>
  <div style=" border-bottom: none:border: px solid #B5B5B5;border-radius: 1px 1px 1px 1px;margin: 0 0 1px; padding: 20px 20px 10px;height:270px; background: none repeat scroll 0 0 #ffffff;color:#666666;font-size:1.2em; ">
  <div style="font-size: 1.6em"> <%= link_to article.title, article_path(article) %></div>
  <div id="tabs">
  <ul id="tabs">
    <li><div style="color:#82b548;font-size: 0.9em;">  <%= time_tag(article.created_at.in_time_zone("Asia/Calcutta")) %> </div></li>
    <li> <div style="color:#4895d1; font-size: 0.9em;">  <%= article.user.username if article.user %></div></li>
    <% if !article.nil? %>
      <li><div style="color:#CCD600; font-size: 0.9em;">  <%= article.comments.size %> comments </div></li>
      <li><div style="color:#CCD600; font-size: 0.9em;"> <%= link_to article.tags.collect(&:name).join(" ") %> </div></li>
     <% end %>
   </ul>
 </div>
    <hr style="border: 1px normal #E0E0F0; margin-top:35px">
    <div style="margin-top:10px; font-size: 1.2 em"> <%= truncate(article.body, :length => 350, :separator => ' ') %></div>
    <div style="margin-top:45px">
       <% if can? :update, @article %>
         <%= link_to "edit",edit_article_path(article), :class => 'btn btn-warning btn' %>
         <%= link_to "delete",article_path(article),:method => :delete,:confirm => 'Are you sure?',:class => 'btn  btn-danger' %>
         <% end %>
        <%= link_to "view more",article_path(article), :class => 'btn btn-info btn-small' %>
       </div>
     </div>
    <% end %>
     <% if can? :create, @article %>
     <%= link_to "Create new Article", new_article_path, :class => 'btn btn-large btn-primary' %>
    <% end %>
   </div>
</td>
<td style="style="width="100%; margin-left:8 00px">

<div class="container">
  <div class="row">
    <div class="span3" style="margin-top:10px">

        <div style="border: 1px solid #B5B5B5;border-radius: 0px 0px 0px 0px; padding: 0px 0px 5px; background: none repeat scroll 0 0 #ffffff;  width: 105%; margin-top:-1365px;margin-left:400px; height:50%;">

            <div style="background-color:#1fb2e8; color:#FFFFFF; font-size: 1.6em"> recent article </div>
          <div style="font-size: 1.3em">
           <% @article_titles.each do |article_title | %>
           <% if !article_title.nil? %>
            <div style="margin-top:15px; margin-left:8px">  <%= link_to truncate(article_title.title, :length => 35, :separator => ' '), article_path(article_title) %></div>
            <% end %>
            <% end %>
        </ul>
      </div>
      </div> <!-- well -->
    </div> <!-- span4 -->
  </div> <!-- row -->
</div> <!-- container -->
<div class="container">
  <div class="row">
    <div class="span3" style="margin-top:10px">

         <div style="border: 1px solid #B5B5B5;border-radius: 0px 0px 0px 0px; padding: 0px 0px 5px; background: none repeat scroll 0 0 #ffffff;  width: 105%; margin-top:-920px;margin-left:400px; height:100%;border-left:1px solid #B5B5B5;">
           <div style="font-size: 1.3em">
           <div style="background-color:#1fb2e8; color:#FFFFFF; font-size: 1.6em"> aticles by tags </div>
           <% @tags.each do |tag| %>
           <%= link_to tag.name, tag, :class => "tag" %>
         <% end %>
        </div>
      </div>
      </div> <!-- well -->
    </div> <!-- span4 -->
  </div> <!-- row -->
</div> <!-- container -->

<div class="container">
  <div class="row">
    <div class="span3" style="margin-top:10px">

        <div style="border: 1px solid #B5B5B5;;border-radius: 0px 0px 0px 0px; padding: 0px 0px 5px; background: none repeat scroll 0 0 #ffffff; width: 105%; margin-top:-1643px;margin-left:400px; height:40%; border-left:1px solid #B5B5B5;">

           <div style="background-color:#1fb2e8; color:#FFFFFF; font-size: 1.8em; margin-left:"> find me here </div>

           <div style="font-size: 1.3em">
           <div style="margin-top:15px; margin-left:8px"> <a href="https://github.com/Vinay50" target="_blank"> GitHub</a> </div>
           <div style="margin-top:12px; margin-left:8px"> <a href="http://stackoverflow.com/users/2096939/vsiingh" target="_blank"> stackoverflow</a> </div>
            <div style="margin-top:12px; margin-left:8px"><a href="https://twitter.com/VieenaySiingh" target="_blank"> Twitter </a> </div>
            <div style="margin-top:12px; margin-left:8px"><a href="https://plus.google.com/u/1/113565492904033788790/about/p/pub" target="_blank" target="_blank"> Google+</a> </div>
            <div style="margin-top:12px; margin-left:8px"><a href="http://www.linkedin.com/profile/view?id=62531573&trk=tab_pro" target="_blank"> Linkedin</a>   </div>
           <div style="margin-top:12px; margin-left:8px">  <a href="https://www.facebook.com/vieenaysiingh" target="_blank">facebook</a> </div>
         </div>
       </div> <!-- well -->
      </div> <!-- span4 -->
     </div> <!-- row -->
   </div> <!-- container -->
 </div>
</td>
</tr>
</table>

app/views/articles/new.html.erb

 <div style="border: 0px solid #1763A4;border-radius: 4px 4px 4px 4px; padding: 20px 20px 10px; background: none repeat scroll 0 0 #ffffff; width: 100%; margin-left:	110px;margin-top:00px">
	<div style="color:#0077CC;font-size: 2.0em">  creating new article </div>
	<%= render :partial => 'form' %>
</div>

app/views/articles/show.html.erb
<div class="row-fluid">
  <div class="span12">
  <div class ="span9">
    <div class ="row-fluid">
      
      <div id="upperborder">
          <div id="lowerborder">
            <div style="color:#1fb2e8;font-size:2.3em;"><%= @article.title %></div>
             <div id="tabs"> 
              <ul id="tabs">
              <li>  <%= time_tag(@article.created_at.in_time_zone("Asia/Calcutta")) %> </li>
              <li>   <%= @article.user.username if @article.user %></li>
              <li>
                 <% if !(@article.comments.empty?) %>
                 (<%= @article.comments.size %>) comments
                 <% else %>
                 (0) comment
                 <% end %>
                 </li>
                 <li>
                 <% @article.tags.each do |tag| %>
                  <%= link_to tag.name, tag_path(tag) %>
                <% end %>     
              </li>
             </ul>
           </div>            

         <hr id="upperline">
         <div style="font-size: 1.2em"><%= @article.body %></div>
       <div id="tabs"> 
          <ul id="tabs">
            <div style="margin-top:20px; margin-left:10px"> <li> <%= link_to "back",articles_path, :class => ''  %></li></div>
             <% if current_user.try (:is_admin) %>
               <div style="margin-top:20px;margin-left:-10px""> <li> <%= link_to "edit", edit_article_path(@article) %></li> </div>
               <div style="margin-top:20px"> <li> <%= link_to "delete",article_path(@article),:method => :delete,:confirm => 'Are you sure?' %></li> </div>
             <% end %>
          </ul>
        </div>       

       <div id="fabs">
         <ul id="fabula">
           <div style="margin-left:540px;margin-top:5px; font-size:1.2em;color:#1fb2e8;">  Viewed: <strong> <%= @article.impressions_count %> times </strong> </div>
           <div style="margin-left:540px;margin-top:5px; font-size:1.2em;color:#1fb2e8;">
           <% if (@article.created_at != @article.updated_at) %>
           edit: <strong> <%= time_ago_in_words(@article.updated_at) %>  ago </strong>
           <% end %></div>
           <div style="margin-left:540px;margin-top:5px; font-size:1.2em;color:#1fb2e8;">
           <% if ! @article.comments.empty? %>
           Active: <strong> <%=  time_ago_in_words(@article.comments.last.created_at) %> ago </strong> 
           <% end %>
           </div>
         </ul>
       </div>
 
       <hr style="border: 1px solid #E0E0F0; margin-top:50px">
       <div id="commentform">
         <%= render :partial => 'comments/comment_form' %>
           <% @article.comments.each do |c| %>
             <% if !c.nil? %>
               <div id ="commentdisplay"> <%= render partial: 'comments/comment', :locals => { :comment => c } %> </div>
             <% end %> 
            <% end %> 
       </div> 
      </div>
     </div>
   </div>
      
       <div class="span3">    
         <div id="popular"> 
          <% if !@most_viewed_articles.empty? %>
            <div id="headerpopular"> most viewed articles </div>
             <% @most_viewed_articles.each do |most_viewed_articles| %>
              <div id="popular-title">  <%= link_to  truncate(most_viewed_articles.title, :length => 35, :separator => ' '),  article_path(most_viewed_articles) %></div>
             <% end %>
          <% end %>
        </div>
     </div>
   </div>
       
       <% if !@related_articles.empty? %>
          <div id = "related-border">
          <div id="related-title"> Related articles </div>
          <% @related_articles.each do | related_article | %>       
          <div id="related-title-link">  <%= link_to  truncate(related_article.title, :length => 35, :separator => ' '),  article_path(related_article) %></div>
        <% end %>
        </div> 
        <% else %>
          <div id="related-border">
          <div id="ygm"> You got us ! </div>
          <div id="nofound"><h3> no related article found :(</h3></div>
          </div> 
        <% end %>
    