config/routes.rb
Mau::Application.routes.draw do
  
  root :to => 'articles#index'
  resources :articles
  resources :dashboard
  resources :tags
  resources :comments
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  resources :articles do
    resources :comments
  end
end 












app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  has_many :taggings, :dependent => :destroy
  has_many :articles, through: :taggings
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
 #before_filter :user_signed_in, only: [:destroy]

   def index
    @tags = Tag.all
   end

	def show
     @tag = Tag.find(params[:id])
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/index.html.erb
<h4> all tags</h4>
<%= @tags.each do |tags| %>
<table>
	<tr>
		<td>
          <%= tags.id%>
       </td>
       <td>
          <%= tags.name %>
       </td>
       <td>
          <%= tags.created_at %>
       </td>
   </tr>
<% end %>

app/views/tags/show.html.erb


<div style="color:#0077CC; font-size: 2.3em"> article(s) with <%= @tag.name %> tag</div>
<div style="border: 0px solid #1763A4;border-radius: 4px 4px 4px 4px; padding: 20px 20px 10px; background: none repeat scroll 0 0 #ffffff; width: 100%; margin-left:110px;margin-top:00px">
<% if !@tag.articles.nil? %>
<div id="tabs"> 
  <ul id="tabs">
  <% @tag.articles.each do |article| %>
    <li><div style="color:#CCD600; font-size: 1.2em;"><%= link_to article.title, article_path(article) %></div></li>
    <li><div style="color:#CCD600; font-size: 1.2em;"> Posted by </div></li>
    <li> <div style="color:#4895d1; font-size: 1.2em">  <%= article.user.username if article.user %></div></li>
       <li><div style="color:#CCD600; font-size: 1.2em;"> at </div></li>
    <li><div style="color:#82b548;">  <%= time_tag(article.created_at.in_time_zone("Asia/Calcutta")) %> </div></li>   
    <% if !article.nil? %>
      <li><div style="color:#CCD600; font-size: 1.2em;">  <%= article.comments.size %> comments </div></li>
     <% end %>
  <% end %>
  </ul>
 </div>
<% end %>
</div>